services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  api:
    build: .
    container_name: projects-api
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/projectsDB
    volumes:
      - ./src/public/uploads:/app/src/public/uploads
    restart: unless-stopped

volumes:
  mongodb_data: